name: Code Check

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Check formatting
        run: flutter format --dry-run --set-exit-if-changed .
      - name: Do static code analysis
        run: dart analyze .